import json
import re
import httpx
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional

class ProviderResponse:
    def __init__(self, content: str = "", thought: str = "", tool_calls: Optional[List[dict]] = None):
        self.content = content
        self.thought = thought
        self.tool_calls = tool_calls or []

class BaseLLMProvider(ABC):
    @abstractmethod
    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        pass

class GeminiProvider(BaseLLMProvider):
    def __init__(self, api_key: str, model: str = "gemini-2.0-flash"):
        self.api_key = api_key
        self.model = model

    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        if not self.api_key:
            raise ValueError("Gemini API key is not configured.")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

        # Convert chat messages to Gemini contents format
        contents = []
        system_instruction = None
        for m in messages:
            if m["role"] == "system":
                system_instruction = {"parts": [{"text": m["content"]}]}
            else:
                role = "user" if m["role"] == "user" else "model"
                contents.append({
                    "role": role,
                    "parts": [{"text": m["content"]}]
                })

        payload: Dict[str, Any] = {
            "contents": contents,
            "generationConfig": {"temperature": temperature}
        }
        if system_instruction:
            payload["systemInstruction"] = system_instruction

        # Convert tool schemas to Gemini function declarations if provided
        if tools_schema:
            function_declarations = []
            for t in tools_schema:
                function_declarations.append({
                    "name": t["name"],
                    "description": t["description"],
                    "parameters": t["parameters"]
                })
            payload["tools"] = [{"functionDeclarations": function_declarations}]

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(url, json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"Gemini API Error ({resp.status_code}): {resp.text}")

            data = resp.json()
            candidates = data.get("candidates", [])
            if not candidates:
                return ProviderResponse(content="No response generated by Gemini.")

            candidate = candidates[0]
            parts = candidate.get("content", {}).get("parts", [])

            content_text = ""
            thought_text = ""
            tool_calls = []

            for part in parts:
                if "text" in part:
                    text_val = part["text"]
                    # Extract thinking tags if present (e.g. <thought>...</thought>)
                    thought_match = re.search(r"<thought>(.*?)</thought>", text_val, re.DOTALL)
                    if thought_match:
                        thought_text += thought_match.group(1).strip()
                        text_val = re.sub(r"<thought>.*?</thought>", "", text_val, flags=re.DOTALL).strip()
                    content_text += text_val
                elif "functionCall" in part:
                    fc = part["functionCall"]
                    tool_calls.append({
                        "name": fc.get("name"),
                        "args": fc.get("args", {})
                    })

            return ProviderResponse(content=content_text, thought=thought_text, tool_calls=tool_calls)

class OpenAIProvider(BaseLLMProvider):
    def __init__(self, api_key: str, model: str = "gpt-4o-mini", base_url: str = "https://api.openai.com/v1"):
        self.api_key = api_key
        self.model = model
        self.base_url = base_url.rstrip("/")

    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        if not self.api_key:
            raise ValueError("API key is not configured for OpenAI/Groq provider.")

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        payload: Dict[str, Any] = {
            "model": self.model,
            "messages": messages,
            "temperature": temperature
        }

        if tools_schema:
            payload["tools"] = [{"type": "function", "function": t} for t in tools_schema]

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(f"{self.base_url}/chat/completions", headers=headers, json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"OpenAI/Groq API Error ({resp.status_code}): {resp.text}")

            data = resp.json()
            choice = data["choices"][0]["message"]
            content = choice.get("content") or ""
            thought = ""
            tool_calls = []

            # Check if model has reasoning_content (DeepSeek / Groq R1)
            if "reasoning_content" in choice:
                thought = choice["reasoning_content"]

            if choice.get("tool_calls"):
                for tc in choice["tool_calls"]:
                    fn = tc.get("function", {})
                    args = {}
                    try:
                        args = json.loads(fn.get("arguments", "{}"))
                    except Exception:
                        pass
                    tool_calls.append({
                        "name": fn.get("name"),
                        "args": args
                    })

            return ProviderResponse(content=content, thought=thought, tool_calls=tool_calls)

class OllamaProvider(BaseLLMProvider):
    def __init__(self, base_url: str = "http://localhost:11434", model: str = "llama3"):
        self.base_url = base_url.rstrip("/")
        self.model = model

    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        url = f"{self.base_url}/api/chat"
        payload = {
            "model": self.model,
            "messages": messages,
            "stream": False,
            "options": {"temperature": temperature}
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(url, json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"Ollama Error ({resp.status_code}): {resp.text}")

            data = resp.json()
            msg = data.get("message", {})
            content = msg.get("content", "")
            return ProviderResponse(content=content)

class LocalFallbackProvider(BaseLLMProvider):
    """
    Built-in Intelligent Reasoning Engine that operates 100% offline without any API keys.
    Understands intent, triggers tools (calculator, code runner, search, file manager),
    and gives rich structured responses.
    """
    async def generate(
        self,
        messages: List[Dict[str, str]],
        tools_schema: Optional[List[dict]] = None,
        temperature: float = 0.7
    ) -> ProviderResponse:
        last_msg = messages[-1]["content"] if messages else ""
        query = last_msg.strip().lower()

        # Check if the last message is a tool result
        if any(m["role"] == "system" and "Tool Observation:" in m["content"] for m in messages[-2:]):
            obs_msg = [m["content"] for m in messages if "Tool Observation:" in m.get("content", "")][-1]
            return ProviderResponse(
                content=f"Here is the result based on execution:\n\n{obs_msg.replace('Tool Observation:', '').strip()}\n\nIs there anything else you would like me to process or analyze?",
                thought="Synthesized the tool execution observation into a structured final response."
            )

        # 1. Math / Calculation detection
        math_match = re.search(r"(\bcalc(?:ulate)?|\bcompute|\beval|\bwhat is|\bhow much is)\s+([0-9\.\s\+\-\*\/\^\(\)\%\,\'\"a-z]+)", query)
        calc_symbols = re.search(r"^[0-9\.\s\+\-\*\/\^\(\)]+$", query)
        if (math_match or calc_symbols) and not any(kw in query for kw in ["code", "python", "script", "file"]):
            expr = math_match.group(2).strip("? .") if math_match else query.strip()
            # Clean expression
            expr = expr.replace("x", "*").replace("times", "*").replace("divided by", "/")
            return ProviderResponse(
                thought=f"User asked for mathematical computation: '{expr}'. Invoking the safe Calculator tool.",
                tool_calls=[{"name": "calculator", "args": {"expression": expr}}]
            )

        # 2. Python Code Execution detection
        if any(kw in query for kw in ["run python", "execute python", "run code", "calculate prime", "fibonacci", "generate code"]):
            # Extract code if present inside backticks
            code_match = re.search(r"```(?:python)?(.*?)```", last_msg, re.DOTALL)
            code = code_match.group(1).strip() if code_match else ""
            if not code:
                # Provide default sample task or prime calculation
                code = "print([x for x in range(2, 50) if all(x % d != 0 for d in range(2, int(x**0.5) + 1))])"
            return ProviderResponse(
                thought="Detected request to execute Python code. Sending to sandboxed code runner tool.",
                tool_calls=[{"name": "code_runner", "args": {"code": code}}]
            )

        # 3. File workspace inspection
        if any(kw in query for kw in ["list file", "show file", "what files", "directory", "dir", "ls"]):
            return ProviderResponse(
                thought="User wants to inspect workspace files. Calling file_manager tool.",
                tool_calls=[{"name": "file_manager", "args": {"action": "list", "path": "."}}]
            )

        # 4. Web search request
        if any(kw in query for kw in ["search web", "google", "search for", "look up", "who is", "latest news"]):
            search_term = re.sub(r"^(search web for|search for|google|search|look up)\s*", "", query).strip("? .")
            return ProviderResponse(
                thought=f"Detected request for web information: '{search_term}'. Calling live web search tool.",
                tool_calls=[{"name": "web_search", "args": {"query": search_term}}]
            )

        # 5. General intelligent response
        return ProviderResponse(
            thought="Local Fallback Engine activated. Formulating structured conversational response.",
            content=(
                f"### 👋 Welcome to **Nexus-AI**!\n\n"
                f"I am running on the **Built-in Local Agent Engine**.\n\n"
                f"I can autonomously reason and execute tasks using my integrated tools:\n"
                f"- 🐍 **Python Sandbox**: Ask me to run code or perform complex algorithms.\n"
                f"- 🌐 **Web Search**: Ask me to search the live web for facts and articles.\n"
                f"- 📁 **File Manager**: Inspect or manage files in your project workspace.\n"
                f"- 🧮 **Calculator**: Precise scientific and arithmetic computations.\n"
                f"- 📚 **RAG Memory**: Drag and drop documents to chat with them.\n\n"
                f"> 💡 **Tip**: You can also connect **Google Gemini**, **OpenAI**, **Groq**, or **Ollama** "
                f"by clicking the **⚙️ Settings** icon in the top navigation bar to unlock state-of-the-art LLM intelligence!"
            )
        )
